---          
apiVersion: v1
kind: Service
metadata:
  name: iibmq1
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 4414
    targetPort: 4414
  - name: http2
    protocol: TCP
    port: 7800
    targetPort: 7800    
  - name: http3
    protocol: TCP
    port: 1414
    targetPort: 1414
  selector:
    app: iibmq1